config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'splash_screens#index'

  authenticated :user do
      resources :categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :transactions
      resources :splash_screens
  end
    get 'users/sign_in' => 'devise/sessions#new'
    get '/categories', to: 'categories#index'
    get '/transactions', to: 'transactions#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :transaction_categories
  has_many :transactions
  validates :name, presence: true
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.includes(:transactions)
  end

  def show
    @category = Category.includes(:transactions).find(params[:id])
    @transactions = @category.transactions
  end

  def new
    @category = Category.new
    @icon_choices = [
      ['🛒', '🛒'],
      ['🛩️', '🛩️'],
      ['🍽️', '🍽️'],
      ['🚗', '🚗'],
      ['🏠', '🏠'],
      ['🛍️', '🛍️'],
      ['🏥', '🏥'],
      ['🎓', '🎓'],
      ['📦', '📦'],
      ['🎮', '🎮']
    ]
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>



</div>

app/views/categories/_form.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="d-flex justify-content-between align-items-center w-100">
    <%= link_to categories_path, class: "navbar-brand text-white", style: "padding: 0;" do %>
      <img src="<%= asset_path('arrow-left.png') %>" alt="" class="logo" style="margin-left: 10px; width: 30px;">
    <% end %>
    <p class="text-center text-white mb-0">Create Category</p>
    <a class="navbar-brand text-right" href="#">
      <img src="<%= asset_path('search-icon.png') %>" alt="" class="logo" style="margin-right: 10px; width: 30px;">
    </a>
  </div>
</nav>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: category) do |form| %>
        <% if category.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
            <ul>
              <% category.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :icon %>
         <%= form.select :icon, @icon_choices, {}, class: "form-control" %>

        </div>

        <div class="form-group">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="d-flex justify-content-between align-items-center w-100">
    <a class="navbar-brand text-white" href="#">
      <img src="<%= asset_path('nav-icon.png') %>" alt="" class="logo" style="margin-left: 10px; width: 30px;">
    </a>
    <p class="text-center text-white mb-0">Categories</p>
    <a class="navbar-brand text-right" href="#">
      <img src="<%= asset_path('search-icon.png') %>" alt="" class="logo" style="margin-right: 10px; width: 30px;">
    </a>
  </div>
</nav>


<div class="notifications">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<p style="color: green"><%= notice %></p>

<div id="categories" class="list-group" style="margin-left: 10px; margin-right: 10px;">
  <% @categories.each do |category| %>
    <a href="<%= category_path(category) %>" class="list-group-item list-group-item-action mb-3" style="margin: 0 auto;">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-inline mb-4">
          <%= category.icon.html_safe %>
        </div>
        <div class="d-inline text-center">
          <h5 class="card-title"><%= category.name %></h5>
        </div>
        <div class="text-lg font-weight-bold">
          <p>$ <%= category.transactions.sum(:amount) %></p>
        </div>
      </div>
    </a>
  <% end %>
</div>


<footer class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: #5fb523;">
  <div class="container">
    <%= link_to "Create new category", new_category_path, class: "btn btn-success btn-block", style: "background-color: #5fb523; width: 100%; border: 1px solid white;" %>
  </div>
</footer>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="d-flex justify-content-between align-items-center w-100">
    <%= link_to categories_path, class: "navbar-brand text-white", style: "padding: 0;" do %>
      <img src="<%= asset_path('arrow-left.png') %>" alt="" class="logo" style="margin-left: 10px; width: 30px;">
    <% end %>
    <p class="text-center text-white mb-0"><%= @category.name %></p>
    <a class="navbar-brand text-right" href="#">
      <img src="<%= asset_path('search-icon.png') %>" alt="" class="logo" style="margin-right: 10px; width: 30px;">
    </a>
  </div>
</nav>


<div class="list-group" style="margin-left: 0; margin-right: 0;">
  <div class="card mb-2">
    <div class="card-body d-flex justify-content-between">
      <div>
        <h5 class="card-title">Total Transactions Amount:</h5>
      </div>
      <div>
        <% total_amount = @category.transactions.sum(:amount) %>
        <p class="card-text">$<%= total_amount %></p>
      </div>
    </div>
  </div>
</div>


<div class="list-group" style="margin-left: 20px; margin-right: 20px;">
  <% @category.transactions.each do |transaction| %>
    <%= link_to transaction, class: "text-decoration-none" do %>
  <div class="card mb-2">
    <div class="card-body d-flex justify-content-between">
      <div>
        <h5 class="card-title"><%= transaction.name %></h5>
      </div>
      <div>
        <% total_amount = @category.transactions.sum(:amount) %>
        <p class="card-text">$<%= transaction.amount %></p>
      </div>
    </div>
  </div>
     <% end %>
  <% end %>
</div>


<footer class="navbar navbar-expand-lg navbar-light fixed-bottom" style="background-color: #5fb523;">
  <div class="container">
    <%= link_to "Add a new transaction", new_transaction_path(category_id: @category.id), class: "btn btn-success btn-block", style: "background-color: #5fb523; width: 100%; border: 1px solid white;" %>
  </div>
</footer>