config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'splash_screens#index'

  authenticated :user do
      resources :categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :transactions
      resources :splash_screens
  end
    get 'users/sign_in' => 'devise/sessions#new'
    get '/categories', to: 'categories#index'
    get '/transactions', to: 'transactions#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.includes(:categories)
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @category = Category.find(params[:category_id]) if params[:category_id].present?
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    category_id = params[:transaction][:category_id]

    puts "Category ID: #{category_id}"
    # @transaction = Transaction.new(author_id: current_user.id, **transaction_params)
    @transaction = Transaction.new(author_id: current_user.id, category_id:, **transaction_params)

    if category_id.present?
      @transaction.category_id = category_id

      respond_to do |format|
        if @transaction.save
          flash[:success] = 'Successfully created a new transaction.'
          format.html { redirect_to category_path(category_id), notice: 'Transaction was successfully created.' }
          format.json { render :show, status: :created, location: @transaction }
        else
          flash[:error] = 'There was an error while creating the transaction.'
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @transaction.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:error] = 'No category was selected for the transaction.'
      render :new
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Transaction was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :category_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="d-flex justify-content-between align-items-center w-100">
    <%= link_to categories_path, class: "navbar-brand text-white", style: "padding: 0;" do %>
      <img src="<%= asset_path('arrow-left.png') %>" alt="" class="logo" style="margin-left: 10px; width: 30px;">
    <% end %>
    <p class="text-center text-white mb-0">New Transaction</p>
    <a class="navbar-brand text-right" href="#">
      <img src="<%= asset_path('search-icon.png') %>" alt="" class="logo" style="margin-right: 10px; width: 30px;">
    </a>
  </div>
</nav>


<div class="container mt-3" style="max-width: 400px; margin: 0 auto;">
  <%= form_with(model: @transaction) do |form| %>
    <% if @transaction.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
        <ul>
          <% @transaction.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-3">
      <%= form.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.text_field :amount, placeholder: "Amount", class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.hidden_field :category_id, value: @category.id %>
    </div>

    <div class="form-group mb-3">
      <%= form.submit "Create Transaction", class: "btn btn-primary", style: "background-color: #3778c2;" %>
    </div>
  <% end %>
</div>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
   $ <%= transaction.amount %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= transaction.category.name %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>
<%= link_to "Categories", categories_path %>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>

<br>

app/views/transactions/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #3778c2;">
  <div class="d-flex justify-content-between align-items-center w-100">
    <%= link_to categories_path, class: "navbar-brand text-white", style: "padding: 0;" do %>
      <img src="<%= asset_path('arrow-left.png') %>" alt="" class="logo" style="margin-left: 10px; width: 30px;">
    <% end %>
    <p class="text-center text-white mb-0"><%= @transaction.name %></p>
    <a class="navbar-brand text-right" href="#">
      <img src="<%= asset_path('search-icon.png') %>" alt="" class="logo" style="margin-right: 10px; width: 30px;">
    </a>
  </div>
</nav>


<p style="color: green"><%= notice %></p>
<div class="container">
  <div id="transactions" class="card mx-auto" style="max-width: 100%;">
    <div class="card-body text-center">
      <h2 class="card-title"><%= @transaction.name %></h2>
      <%= render @transaction %>
      <div class="btn-group-vertical" role="group" aria-label="Vertical radio toggle button group">
        <%= button_to "Delete transaction", @transaction, method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  </div>
</div>